name: Access Cached MAST Files

on:
  workflow_dispatch:
    inputs:
      uris:
        description: 'List of URIs to access (comma-separated)'
        required: false
        default: 'jw02732004001_02103_00004_mirifushort_x1d.fits,
                  jw01538160001_16101_00004_nrs1_s2d.fits,
                  jw02727-o002_t062_nircam_clear-f090w_i2d.fits,
                  jw02732004001_02103_00004_mirifushort_s3d.fits'
        type: string

jobs:
  access-cache:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install astroquery

    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ./
        key: mast-cache-${{ github.run_number }}
        restore-keys: |
          mast-cache-

    - name: List files
      run: |
        ls -la || echo "No files found"

    - name: Create astroquery access script
      run: |
        cat > download_script.py << 'EOF'
        import os
        from astroquery.mast import MastMissions, Observations
        
        # Get URIs from environment variable
        uris_input = os.environ.get('URIS')
        uris = [uri.strip() for uri in uris_input.split(',')]
        
        # Initialize MAST missions
        mast = MastMissions()
        mast.mission = 'jwst'

        for i, uri in enumerate(uris):
            full_uri = '_'.join(uri.split('_')[:3])+'/'+uri
            print(f'\nProcessing URI {i+1}/{len(uris)}: {uri}')
            
            try:
                mast.download_file(full_uri, local_path='./', cache=True)
            except Exception as e:
                print(f'Error processing {uri}: {e}')

            observations_uri = f'mast:jwst/product/{full_uri}'
            print(f'\nObservations.download_file {observations_uri}')
            try:
                Observations.download_file(observations_uri, local_path='./', cache=True)
            except Exception as e:
                print(f'Error downloading {observations_uri}: {e}')

        print('\nDownload process completed!')
        EOF

    - name: Run access script
      run: |
        python download_script.py
      env:
        URIS: ${{ inputs.uris }}